run:
  modules-download-mode: readonly
  deadline: 5m

output:
  format: line-number

linters:
  enable:
    - bodyclose
    - dupl
    - funlen
    - goconst
    - gocyclo
    - gofmt
    - goprintffuncname
    - lll
    - misspell
    - nolintlint
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  funlen:
    lines: 110
    statements: 50

  lll:
    line-length: 140

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - errcheck
    - path: cmd/api/route
      linters:
        - funlen
    - path: pkg/mapper/package_mapper\.go
      linters:
        - funlen

service:
  golangci-lint-version: 1.27.x # use the fixed version to not introduce new linters unexpectedly
